### ISSUE TITLE
ArrayIndexOutOfBoundsException when running with no. compartments > 3

### ISSUE THREAD

**Issue by larsupb** [hschneid/xfvrp#25]
`
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at xf.xfvrp.report.RouteReportSummary.setPickupLoad(RouteReportSummary.java:134)
	at xf.xfvrp.report.RouteReportSummary.add(RouteReportSummary.java:109)
	at xf.xfvrp.report.RouteReport.add(RouteReport.java:46)
	at xf.xfvrp.report.build.ReportBuilder.getRouteReport(ReportBuilder.java:53)
	at xf.xfvrp.report.build.ReportBuilder.getReport(ReportBuilder.java:40)
	at xf.xfvrp.opt.FullRouteMixedFleetHeuristic.execute(FullRouteMixedFleetHeuristic.java:67)
	at xf.xfvrp.XFVRP.executeRoutePlanning(XFVRP.java:81)
`

**Comment by larsupb** [comment]
[Bugfix](https://github.com/hschneid/xfvrp/commit/c419204faf23cfff5226c67bb3de4bb72ac196c8)

**Comment by hschneid** [comment]
Solved with version 1.4.1

**Comment by larsupb** [comment]
Yep, solved :-)
